/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about/About.vue')['default']
    CallToAction: typeof import('./src/components/CallToAction.vue')['default']
    CardProject: typeof import('./src/components/CardProject.vue')['default']
    Contact: typeof import('./src/components/contact/Contact.vue')['default']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    ExperienceTimeLine: typeof import('./src/components/ExperienceTimeLine.vue')['default']
    Home: typeof import('./src/components/home/Home.vue')['default']
    InfoInterest: typeof import('./src/components/InfoInterest.vue')['default']
    InformationCard: typeof import('./src/components/InformationCard.vue')['default']
    Location: typeof import('./src/components/Location.vue')['default']
    NotFound: typeof import('./src/components/not-found/NotFound.vue')['default']
    Project: typeof import('./src/components/project/Project.vue')['default']
    ProjectFeature: typeof import('./src/components/ProjectFeature.vue')['default']
    SkillSection: typeof import('./src/components/SkillSection.vue')['default']
    State: typeof import('./src/components/State.vue')['default']
    VMap: typeof import('vue-map-ui')['VMap']
    VMapArcGisAeroTileLayer: typeof import('vue-map-ui')['VMapArcGisAeroTileLayer']
    VMapArcGisTileLayer: typeof import('vue-map-ui')['VMapArcGisTileLayer']
    VMapAttributionControl: typeof import('vue-map-ui')['VMapAttributionControl']
    VMapControlPosition: typeof import('vue-map-ui')['VMapControlPosition']
    VMapDefaultIcon: typeof import('vue-map-ui')['VMapDefaultIcon']
    VMapDivIcon: typeof import('vue-map-ui')['VMapDivIcon']
    VMapDivMarker: typeof import('vue-map-ui')['VMapDivMarker']
    VMapGoogleTileLayer: typeof import('vue-map-ui')['VMapGoogleTileLayer']
    VMapIcon: typeof import('vue-map-ui')['VMapIcon']
    VMapIconMarker: typeof import('vue-map-ui')['VMapIconMarker']
    VMapLayersControl: typeof import('vue-map-ui')['VMapLayersControl']
    VMapLocateControl: typeof import('vue-map-ui')['VMapLocateControl']
    VMapMapboxTileLayer: typeof import('vue-map-ui')['VMapMapboxTileLayer']
    VMapMarker: typeof import('vue-map-ui')['VMapMarker']
    VMapOpenTransportTileLayer: typeof import('vue-map-ui')['VMapOpenTransportTileLayer']
    VMapOsmTileLayer: typeof import('vue-map-ui')['VMapOsmTileLayer']
    VMapPane: typeof import('vue-map-ui')['VMapPane']
    VMapPinIcon: typeof import('vue-map-ui')['VMapPinIcon']
    VMapPinMarker: typeof import('vue-map-ui')['VMapPinMarker']
    VMapScaleControl: typeof import('vue-map-ui')['VMapScaleControl']
    VMapTileLayer: typeof import('vue-map-ui')['VMapTileLayer']
    VMapZoomControl: typeof import('vue-map-ui')['VMapZoomControl']
  }
}
